version: 2
jobs:
  build:    
    working_directory: ~/repo

    docker:
      - image: marem/circleci-openjdk-oc

    steps:
      - checkout

      - restore_cache:
          key: circleci-hello-world-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-hello-world-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/hello-world-0.1.0.jar

      - deploy: 
          command: |
              oc login -u ${CLUSTER_USERNAME} -p ${CLUSTER_PASSWORD} ${CLUSTER_URL}
              oc new-project ${PROJECT_NAME}
              oc project ${PROJECT_NAME}
              oc start-build ${APP_NAME} --from-dir=.


