version: 2
jobs:
    init-manawa-project:
        docker:
            - image: marem/circleci-openjdk-oc

        steps:
            - checkout

            - deploy: 
                command: |
                    sh oc-create.sh

    build-sources:
        working_directory: ~/repo

        docker:
            - image: marem/circleci-openjdk-oc

        steps:
            - restore_cache:
                key: circleci-hello-world-{{ checksum "pom.xml" }}
            
            - run: mvn dependency:go-offline
            
            - save_cache:
                paths:
                    - ~/.m2
                key: circleci-hello-world-{{ checksum "pom.xml" }}
            
            - run: mvn package
            
            - store_test_results:
                path: target/surefire-reports
            
            - store_artifacts:
                path: target/hello-world-0.1.0.jar
    
    docker-build:
        requires: 
            - init-manawa-project
            - build-sources

        docker:
            - image: docker:17.05.0-ce-git
        steps:
            - deploy:
                command: |
                    docker login -u ${CLUSTER_USERNAME} -p (oc whoami -t) ${DOCKER_REGISTRY_URL}
                    docker build -t ${DOCKER_REGISTRY_URL}/${PROJECT_NAME}/hello-world:latest .
                    docker push ${DOCKER_REGISTRY_URL}/${PROJECT_NAME}/hello-world:latest


workflows:
    version: 2
    deploy:
        jobs:
            - init-manawa-project
            - build-sources
            - docker-build
        


