version: 2
jobs:
    build:
        docker:
            - image: circleci/openjdk

        steps:
            - checkout

            - restore_cache:
                key: circleci-hello-world-{{ checksum "pom.xml" }}
            
            - run: mvn dependency:go-offline
            
            - save_cache:
                paths:
                    - ~/.m2
                key: circleci-hello-world-{{ checksum "pom.xml" }}
            
            - run: mvn package
            
            - store_test_results:
                path: target/surefire-reports
            
            - store_artifacts:
                path: target/hello-world-0.1.0.jar
            
            - persist_to_workspace:
                root: /home/circleci/project
                paths:
                    - target/hello-world-0.1.0.jar

    init-manawa-project:
        docker:
            - image: marem/circleci-openjdk-oc

        steps:
            - checkout
            
            - deploy: 
                command: |
                    sh oc-create.sh
            
    docker-deploy:        
        docker:
            - image: marem/circleci-docker-oc
            
        steps:
            - checkout

            - attach_workspace:
                at: /home/circleci/project
            
            - setup_remote_docker:
                version: 17.05.0-ce

            - run:
                command: |
                    docker build -t ${DOCKER_REGISTRY_URL}/${PROJECT_NAME}/hello-world:latest .
                    docker login -u ${CLUSTER_USERNAME} -p $(oc whoami -t) ${DOCKER_REGISTRY_URL}
                    docker push ${DOCKER_REGISTRY_URL}/${PROJECT_NAME}/hello-world:latest
    
    sync-manawa:
        docker:
            - image: marem/circleci-openjdk-oc

        steps:
            - checkout
            
            - deploy: 
                command: |
                    oc apply -f kubernetes/hello-world-deployment.yml
                    oc apply -f kubernetes/hello-world-service.yml
                    oc apply -f kubernetes/hello-world-route.yml
            
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - init-manawa-project
            - docker-deploy:
                requires: 
                    - init-manawa-project
            - sync-manawa:
                requires: 
                    - docker-deploy
    