version: 2
jobs:
    build:
        working_directory: ~/repo

        docker:
            - image: marem/circleci-openjdk-oc

        steps:
            - checkout

            - restore_cache:
                key: circleci-hello-world-{{ checksum "pom.xml" }}
            
            - run: mvn dependency:go-offline
            
            - save_cache:
                paths:
                    - ~/.m2
                key: circleci-hello-world-{{ checksum "pom.xml" }}
            
            - run: mvn package
            
            - store_test_results:
                path: target/surefire-reports
            
            - store_artifacts:
                path: target/hello-world-0.1.0.jar

            - setup_remote_docker:
                docker_layer_caching: true
                version: 17.05.0-ce
            
            - run:
                command: |
                    docker login -u ${CLUSTER_USERNAME} -p $(oc whoami -t) ${DOCKER_REGISTRY_URL}
                    docker build -t ${DOCKER_REGISTRY_URL}/${PROJECT_NAME}/hello-world:latest .
                    docker push ${DOCKER_REGISTRY_URL}/${PROJECT_NAME}/hello-world:latest

            - deploy: 
                command: |
                    oc apply -f kubernetes/hello-world-deployment.yml
                    oc apply -f kubernetes/hello-world-service.yml
                    oc apply -f kubernetes/hello-world-route.yml
