version: 2
jobs:
    init-manawa-project:
        docker:
            - image: marem/circleci-openjdk-oc

        steps:
            - checkout
            
            - deploy: 
                command: |
                    sh oc-create.sh

    build:
        docker:
            - image: circleci/openjdk

        steps:
            - checkout

            - restore_cache:
                key: circleci-hello-world-{{ checksum "pom.xml" }}
            
            - run: mvn dependency:go-offline
            
            - save_cache:
                paths:
                    - ~/.m2
                key: circleci-hello-world-{{ checksum "pom.xml" }}
            
            - run: mvn package
            
            - store_test_results:
                path: target/surefire-reports
            
            - store_artifacts:
                path: target/hello-world-0.1.0.jar
            
            - persist_to_workspace:
                root: ~/project
                paths:
                    - target/hello-world-0.1.0.jar
            
    docker-deploy:        
        machine: true
            
        steps:
            - checkout

            - attach_workspace:
                at: ~/project
            
            - run:
                name: Configure docker daemon
                command: |
                    echo "{\"insecure-registries\": [\"${DOCKER_REGISTRY_URL}\"]}" > /etc/docker/daemon.json
                    sudo service docker restart

            - run:
                command: |
                    docker build -t ${DOCKER_REGISTRY_URL}/${PROJECT_NAME}/hello-world:latest .
                    docker login -u ${CLUSTER_USERNAME} -p ${CLUSTER_PASSWORD} ${DOCKER_REGISTRY_URL}
                    docker push ${DOCKER_REGISTRY_URL}/${PROJECT_NAME}/hello-world:latest
    
    sync-manawa:
        docker:
            - image: marem/circleci-openjdk-oc

        steps:
            - checkout
            
            - deploy: 
                command: |
                    oc apply -f kubernetes/hello-world-deployment.yml
                    oc apply -f kubernetes/hello-world-service.yml
                    oc apply -f kubernetes/hello-world-route.yml
            
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - init-manawa-project
            - build
            - docker-deploy:
                requires: 
                    - init-manawa-project
                    - build
            - sync-manawa:
                requires: 
                    - docker-deploy
    