version: 2
jobs:
    init-manawa-project:
        docker:
            - image: marem/circleci-openjdk-oc

        steps:
            - checkout

            - deploy: 
                command: |
                    sh oc-create.sh

    build-sources:    
        working_directory: ~/repo

        docker:
            - image: marem/circleci-openjdk-oc

        steps:
            - checkout

            - restore_cache:
                key: circleci-hello-world-{{ checksum "pom.xml" }}
            
            - run: mvn dependency:go-offline
            
            - save_cache:
                paths:
                    - ~/.m2
                key: circleci-hello-world-{{ checksum "pom.xml" }}
            
            - run: mvn package
            
            - store_test_results:
                path: target/surefire-reports
            
            - store_artifacts:
                path: target/hello-world-0.1.0.jar

workflows:
    version: 2
    deploy:
        jobs:
            - init-manawa-project
            - build-sources
        


